### ISSUE TITLE
node src/themes/capybara/scripts/generate-local-config.js

### ISSUE THREAD

**Issue by wmycco1** [DivanteLtd/vsf-capybara#504]
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'semver/functions/inc'
Require stack:
- /var/www/jblab.ru/src/themes/capybara/scripts/generate-local-config.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/var/www/jblab.ru/src/themes/capybara/scripts/generate-local-config.js:5:19)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/www/jblab.ru/src/themes/capybara/scripts/generate-local-config.js'
  ]
}

**Comment by ghost1mgl** [comment]
does it have been solved because I am getting same error
